networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.25.1
    container_name: gitea
    environment:
      - TZ=${TIMEZONE:-UTC}
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${PG_DB:-gitea}
      - GITEA__database__USER=${PG_USER:-gitea}
      - GITEA__database__PASSWD=${PG_PASS:-gitea}
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT:-22}
      - GITEA__server__ROOT_URL=${GITEA_WEB_URL:-http://localhost:3000/}
      - GITEA__mailer__ENABLED=${GITEA_MAILER_ENABLED:-false}
      - GITEA__mailer__FROM=${GITEA_MAILER_FROM:-}
      - GITEA__mailer__PROTOCOL=${GITEA_MAILER_PROTOCOL:-smtps}
      - GITEA__mailer__SMTP_ADDR=${GITEA_MAILER_HOST:-}
      - GITEA__mailer__SMTP_PORT=${GITEA_MAILER_PORT:-465}
      - GITEA__mailer__USER=${GITEA_MAILER_USER:-}
      - GITEA__mailer__PASSWD="""${GITEA_MAILER_PASS:-}"""
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_WEB_PORT:-3000}:3000"
      - "${GITEA_SSH_PORT:-22}:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE:-UTC}
      - POSTGRES_USER=${PG_USER:-gitea}
      - POSTGRES_PASSWORD=${PG_PASS:-gitea}
      - POSTGRES_DB=${PG_DB:-gitea}
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data